<a href="https://colab.research.google.com/github/Haris-09/Deep-Learning/blob/main/ANN_using_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

import torch
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim

In [2]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "zoo.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "uciml/zoo-animal-classification",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df.head()

/tmp/ipython-input-2-609020518.py:10: DeprecationWarning: load_dataset is deprecated and will be removed in a future version.
  df = kagglehub.load_dataset(


100%|██████████| 4.27k/4.27k [00:00<00:00, 2.35MB/s]


animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

In [3]:
df.drop(columns=['animal_name'], inplace=True)
df.head()

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  backbone  \
0     1         0     0     1         0        0         1        1         1   
1     1         0     0     1         0        0         0        1         1   
2     0         0     1     0         0        1         1        1         1   
3     1         0     0     1         0        0         1        1         1   
4     1         0     0     1         0        0         1        1         1   

   breathes  venomous  fins  legs  tail  domestic  catsize  class_type  
0         1         0     0     4     0         0        1           1  
1         1         0     0     4     1         0        1           1  
2         0         0     1     0     1         0        0           4  
3         1         0     0     4     0         0        1           1  
4         1         0     0     4     1         0        1           1

In [4]:
features = df.iloc[:,0:-1]
target = df.iloc[:,-1]

In [5]:
features.dtypes

hair        int64
feathers    int64
eggs        int64
milk        int64
airborne    int64
aquatic     int64
predator    int64
toothed     int64
backbone    int64
breathes    int64
venomous    int64
fins        int64
legs        int64
tail        int64
domestic    int64
catsize     int64
dtype: object

In [6]:
X = features.to_numpy()
y = target.to_numpy()

In [7]:
# Instantiate dataset class
dataset = TensorDataset(torch.tensor(X), torch.tensor(y))

# Access an individual
input_sample, label_sample = dataset[0]
print(input_sample, label_sample)

tensor([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 4, 0, 0, 1]) tensor(1)


In [8]:
batch_size = 2
shuffle = True

# Create a DataLoader
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

In [9]:
# iterate over the dataloader
for batch_inputs, batch_labels in dataloader:
    print(batch_inputs, batch_labels)

tensor([[0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 8, 0, 0, 1],
        [1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 4, 1, 0, 1]]) tensor([7, 1])
tensor([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 8, 1, 0, 0],
        [0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 0]]) tensor([7, 2])
tensor([[1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 6, 0, 0, 0],
        [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 4, 1, 0, 1]]) tensor([6, 1])
tensor([[0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1],
        [0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 2, 1, 0, 0]]) tensor([4, 2])
tensor([[0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 2, 1, 0, 0],
        [0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 4, 1, 0, 0]]) tensor([2, 5])
tensor([[0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0],
        [0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 2, 1, 0, 1]]) tensor([4, 2])
tensor([[1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 2, 1, 0, 1],
        [0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0]]) tensor([1, 4])
tensor([[1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 2, 1, 0, 0],
        [1, 0, 1, 

In [10]:
# Create a model
model = nn.Sequential(nn.Linear(16, 2),
                      nn.Linear(2,7))

# Create the loss and optimizer
criterion = nn.CrossEntropyLoss()
# optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [11]:
features = torch.tensor(features.values, dtype=torch.float32)
target = torch.tensor(target.values, dtype=torch.long)

In [12]:
target = target-1

In [13]:
num_epochs = 20
for epoch in range(num_epochs):

  outputs = model(features)
  loss = criterion(outputs, target)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss.item()}")

Epoch 1/20, Loss: 2.1072795391082764
Epoch 2/20, Loss: 2.1037814617156982
Epoch 3/20, Loss: 2.1003167629241943
Epoch 4/20, Loss: 2.0968856811523438
Epoch 5/20, Loss: 2.0934884548187256
Epoch 6/20, Loss: 2.090125560760498
Epoch 7/20, Loss: 2.0867958068847656
Epoch 8/20, Loss: 2.083500623703003
Epoch 9/20, Loss: 2.0802385807037354
Epoch 10/20, Loss: 2.0770092010498047
Epoch 11/20, Loss: 2.073812246322632
Epoch 12/20, Loss: 2.070646286010742
Epoch 13/20, Loss: 2.0675103664398193
Epoch 14/20, Loss: 2.0644030570983887
Epoch 15/20, Loss: 2.0613231658935547
Epoch 16/20, Loss: 2.0582683086395264
Epoch 17/20, Loss: 2.055237293243408
Epoch 18/20, Loss: 2.05222749710083
Epoch 19/20, Loss: 2.049237012863159
Epoch 20/20, Loss: 2.0462636947631836


In [14]:
input_tensor = torch.tensor([[6]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
print(output)

tensor([[0.9975]])
